version: '3.8'

# Production overrides for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:
  redis:
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  stock_agent_api:
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
      replicas: 2
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=sqlite:///./data/stocks.db
      - CACHE_TTL=600  # 10 minutes for production
      - LOG_LEVEL=WARNING
      - DEBUG=False
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  stock_agent_frontend:
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    environment:
      - API_BASE_URL=http://stock_agent_api:8000
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

  # Production reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: stock_agent_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl/certs:ro
    depends_on:
      - stock_agent_api
      - stock_agent_frontend
    networks:
      - stock_network
    restart: unless-stopped
